ovh/ovh-ui-kit

- packages/oui-table/_mixins.less
> fix(oui-table): remove spacing between cells when Bootstrap is not loaded

- packages/oui-modal/_normalize.less
- packages/oui-modal/modal.less
default font => as defined by base-font mixin.
Signed-off-by: Mathieu Boulianne <mathieu.boulianne@corp.ovh.com>
> fix(oui-modal): load the correct font

- README.md
- packages/oui-formfield/README.md
I noticed that the name of this component can still be changed at any moment but I'd like to keep the README.md file sync.
> docs(integration): fix oui-formfield path.

- packages/oui-modal/README.md
- packages/oui-modal/_mixins.less
- packages/oui-modal/_variables.less
- packages/oui-progress/_mixins.less
- packages/oui-progress/_variables.less
- packages/oui-radio/_mixins.less
- packages/oui-radio/_variables.less
Inherithing font-size from parents was causing damage in some cases.
> fix(font): fix font-size in differents components.  

- packages/oui-input-group/_mixins.less
:ambulance: fix(oui-input-group): min-height missing on oui-button
> fix(oui-input-group): min-height missing on oui-button

- packages/oui-input-group/_mixins.less
max-width wasn't applied correctly only on firefox, so I fixed it.
> bugfix(oui-input-group): fix max-width on numeric input group on firefox

- packages/oui-loader/_mixins.less
- packages/oui-loader/loader.less
By default, the loader has no alignment and is `display: block`. 
90% of the use of `<oui-loader>` in managers are inline loaders in a text-centered container for a page/view loading:
```
<div class="text-center" data-ng-if="ctrl.loading">
<oui-loader inline="true"></oui-loader>
</div>
```
For the use we make of it, `.oui-loader__container` will be more useful with a `margin: auto`. 
And we could replace all of these by:
```
<oui-loader data-ng-if="ctrl.loading"></oui-loader>
```
It will not impact the inline one
> fix(oui-loader): add centered alignment by default

- packages/oui-button/README.md
- packages/oui-button/_mixins.less
- packages/oui-input-group/README.md
Demo: 
- [oui-button](http://dev_fix_oui_button_icon_only.ui-kit.ovh/#!/ovh-ui-kit/button)
- [oui-input-group](http://dev_fix_oui_button_icon_only.ui-kit.ovh/#!/ovh-ui-kit/input-group)
The icon on `oui-button_icon-only` modifier was kept black and was not grayed out.
> fix(oui-button): disable state when icon only

- packages/oui-modal/_mixins.less
This is a fix to display loader background over ui-select and oui-message
> fix(oui-modal): display modal loader over all elements

- package.json
https://github.com/flatpickr/flatpickr/releases/tag/v4.5.0
Resolves the logs `Error{}` when launching the unit tests
> chore(oui-calendar): bump version of flatpickr to v4.5.0

- packages/oui-icons/fonts.less
- packages/oui-typography/fonts.less
To be loaded first, the WOFF2 declaration must be placed above WOFF.
Currently the WOFF2 fonts are never loaded... the modern browsers respect the order priority in `url()` (see ["Note" section](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=en#format_selection))
This small fix will increase our webperf on all projects using ui-kit 👌
> fix: enable woff2 loading

- packages/oui-datagrid/datagrid.less
39a6824 — fix(oui-datagrid): add missing margin-bottom to extra-top 
capture before:
capture after:
/cc @jleveugle @Jisay @frenautvh @cbourgois @AxelPeter
> fix(oui-datagrid): add missing margin-bottom to extra-top

- packages/oui-criteria-adder/criteria-adder.less
d155c84 — fix(oui-criteria-adder): set padding on four sides
capture before:
capture after:
/cc @jleveugle @Jisay @frenautvh @cbourgois @AxelPeter
> fix(oui-criteria-adder): set padding on four sides

- .github/CODEOWNERS
ac89517 - fix: use the right codeowners syntax
/cc @jleveugle @Jisay @frenautvh @cbourgois
> fix: use the right codeowners syntax

- packages/oui-datagrid/_mixins.less
Columns next to sticky columns are cropped. This fix the cropping by removing the useless calculation.
> fix(oui-datagrid): fix sticky columns

- packages/oui-collapsible/_normalize.less
- packages/oui-criteria-adder/_normalize.less
- packages/oui-criteria-adder/criteria-adder.less
- packages/oui-datagrid/_normalize.less
- packages/oui-field/_normalize.less
- packages/oui-guide-menu/guide-menu.less
- packages/oui-header-tabs/header-tabs.less
- packages/oui-input-group/_normalize.less
- packages/oui-input-group/input-group.less
- packages/oui-message/_normalize.less
- packages/oui-page-header/_normalize.less
- packages/oui-pagination/_normalize.less
- packages/oui-pagination/pagination.less
- packages/oui-radio-toggle-group/_normalize.less
- packages/oui-radio/_normalize.less
- packages/oui-select-picker/_normalize.less
- packages/oui-select/_normalize.less
- packages/oui-skeleton/_normalize.less
- packages/oui-skeleton/skeleton.less
- packages/oui-spinner/_normalize.less
- packages/oui-spinner/spinner.less
- packages/oui-switch/_normalize.less
- packages/oui-switch/switch.less
- packages/oui-textarea/_normalize.less
Some of our custom tags haven't default style. This could lead to have block elements in inline elements.
It could help older browsers to know what to do with these unknown tags.
> fix: fix default style for custom tags

- packages/oui-status/status.less
0e83f86 - fix(oui-status): set border to none when it's used on a button element 
Some part of the application is applying `oui-status` directly on `<button>` element which ends with this result:
ref: https://github.com/ovh-ux/ovh-module-exchange/blob/master/src/exchange/domain/domain.html#L116
/cc @AxelPeter @FredericEspiau @JeremyDec @euhmeuh
> fix(oui-status): set border to none when it's used on a button element

- packages/oui-navbar/_mixins.less
d59e93c — fix(oui-navbar): center aside links
Before:
After:
> fix(oui-navbar): center aside links

- packages/oui-checkbox/_mixins.less
- packages/oui-list/_mixins.less
- packages/oui-popover/popover.less
- packages/oui-radio/_mixins.less
feat: remove unneeded user-select
As we are willing to use complex content inside these components, it might be interesting for the user to be able to select the inner content in order to have various uses (like copy-pasting contents, prices, ...)
However, I kept the `user-select: none` for the components that really don't need to be selected : oui-button, oui-file, oui-tooltip and oui-navbar
User will be able to select content inside these components
As a result, it might select the content when not needed (for instance when checking a checkbox)
> fix: remove unneeded user-select

- packages/oui-modal/_mixins.less
b459a92 — fix(oui-modal): remove loader absolute position
/cc @jleveugle @AxelPeter @marie-j
> fix(oui-modal): remove loader absolute position

- packages/oui-navbar/navbar.less
Apply default style to `oui-navbar-dropdown` direct child links
Allow to wrap `oui-navbar-dropdown` in HTML elements/components
> feat(oui-navbar): add dropdown links style

- packages/oui-navbar/navbar.less
Add ellipsis if menu title is too long
Avoid having multiple lines menu title
> feat(oui-navbar): truncate if menu title is too long

- packages/oui-icons/fonts.less
- packages/oui-typography/fonts.less
perf(oui-typography): font rendering configuration
A new CSS feature inside @font-face definition is font-display, which permits to set a way of
displaying/awaiting the font-family. 
(see: https://developers.google.com/web/updates/2016/02/font-display)
I arbitrarily choose a font-display:block for "Oui Icons" and font-display:fallback for "Source Sans Pro", but it can be debated.
(FYI, CanIUse support : https://caniuse.com/#feat=css-font-rendering-controls)
> perf(oui-typography): font rendering configuration

- packages/oui-popover/popover.less
6fd6dca — fix(oui-popover): set white-space to normal
ref: 
/cc @jleveugle @marie-j @AxelPeter
> fix(oui-popover): set white-space to normal

- packages/oui-radio/_variables.less
fix(oui-radio): wrong font-size for oui-radio m-thumbnail 
oui-radio label font-size was 19px, it should be like oui-checkbox, 24px
>  fix(oui-radio): wrong font-size for oui-radio m-thumbnail 

- packages/oui-guide-menu/guide-menu.less
Adapt style to be able to use guides icon in guides menu
> feat(oui-icons): use guides icon in guides menu

- README.md
# Remove deprecated link to ovh-ui-kit-documentation
6e75a2e - docs(readme): remove deprecated link to ovh-ui-kit-documentation
module is now named as `@ovh-ux/ui-kit`
> docs(readme): remove deprecated link to ovh-ui-kit-documentation

- packages/components/tabs/README.md
3b06a45 - docs(tabs): set right type to the checked attribute
> docs(tabs): set right type to the checked attribute

- packages/components/clipboard/src/js/clipboard.html
6f25724 - fix(clipboard): set button type
- No QC required.
ref: https://github.com/ovh-ux/ovh-ui-angular/pull/397
> fix(clipboard): set button type

- packages/components/criteria/src/js/adder/criteria-adder.html
To avoid the dropdown menu to change its width when we change filters value, all fields has been set to `m`.
> fix(criteria): fix fields size to medium

- packages/components/select/src/js/select.controller.js
UK-98
When you open a `oui-select` and click on another one, the previously opened select doesn't close.
> fix(select): close others opened select on opening

- packages/oui-checkbox/_mixins.less
The input have an absolute position but not its parent which can cause weird behaviour when included within other components
> fix(oui-checkbox): add relative position

- packages/oui-datagrid/_mixins.less
Prevent a vertical scroll from being displayed
When adding a `oui-clipboard` the hidden `tooltip` makes the datagrid container overflow with a scroll. this scroll doesn't apply on all datagrid, it excludes the `oui-action-menu`
Example : MSB-31
> fix(oui-datagrid): prevent scroll from displaying inside the datagrid

- packages/oui-button/_variables.less
MANAGER-2779
Remove the default max-width of `.oui-button` by setting it to `100%`.
> fix(button): set max-width to 100%

- packages/apps/workshop/stories/components/tile.stories.js
- packages/components/tile/README.md
- packages/components/tile/src/js/definition/tile-definition.component.js
- packages/components/tile/src/js/definition/tile-definition.controller.js
- packages/components/tile/src/js/definition/tile-definition.html
- packages/components/tile/src/js/tile.spec.js
- add transclude `<oui-tile-term>`
- add transclude `<oui-tile-actions>`
- update stories
- update documentation
- update unit tests
Allow to add custom tags, to facilitate the migration.
For example:
```html
<div class="oui-tile__item">
<dl class="oui-tile__definition">
<dt class="oui-tile__term">
<service-expiration-label></service-expiration-label>
</dt>
<dd class="oui-tile__description">
<service-expiration-date></service-expiration-date>
</dd>
</dl>
<div class="oui-tile__actions">
<service-expiration-date></service-expiration-date>
</div>
</div>
```
> feat(tile): add transclude for term and actions

- packages/components/numeric/src/js/numeric.controller.js
- packages/components/numeric/src/js/numeric.html
- packages/components/numeric/src/js/numeric.spec.js
Allow OUI numeric value to be changed using keyboard
1. Value in OUI numeric can be changed/removed/deleted using keyboard
2. Showing error if value is empty, less than min or more than max
3. Changed and added new test cases
Its possible to update numeric value using keyboard always
none
MBP-505
> fix(oui-numeric): cant change value using keyboard

- packages/components/numeric/src/js/numeric.controller.js
- packages/components/numeric/src/js/numeric.spec.js
01196f09 — fix(oui-numeric): allow custom min and max values
* https://github.com/ovh-ux/ovh-ui-angular/pull/430
> fix(oui-numeric): allow custom min and max values

- packages/apps/workshop/stories/components/header.stories.js
- packages/components/header/src/js/tabs/header-tabs.controller.js
- packages/components/header/src/js/tabs/header-tabs.html
- packages/components/header/src/js/tabs/header-tabs.spec.js
- packages/components/header/src/less/header-tabs.less
- Remove $interval animation to prefer CSS animation
- Simplify the code for the scrolling to avoid value calculation, and rely on tabs `offsetLeft` value
> feat(header-tabs): update tabs scrolling to allow scroll tab by tab

- packages/components/dropdown/src/js/trigger/dropdown-trigger.controller.js
fix(oui-dropdown): afterClose should remove the focus
- https://github.com/ovh-ux/ovh-ui-angular/pull/449
Focus of the element is correctly removed by using [`.blur()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/blur).
None.
None.
- No quality check required.
Signed-off-by: Antoine Leblanc <antoine.leblanc@corp.ovh.com>
> fix(oui-dropdown): afterClose should remove the focus

- packages/base/core/src/less/_variables.less
Remove max-height on notification description, that comes from previous guidelines
> fix(navbar): remove max-height on notification description

- packages/components/select/src/less/select.less
The mixin was misplaced. The states colors was applied on the wrong element.
> fix(select): fix states colors

- .stylelintrc.json
- packages/base/core/src/less/variables/components/button.less
Having value `0` without unit in a `calc()` cause error `invalid value`.
To resolve the problem, I've added `px` to the value.
This has no side effect, except resolving this issue.
> fix(button): fix invalid calculated value

- packages/base/core/src/less/fonts.less
refactor: add font-display property for oui-icons
`font-display: block;` hides the currently loading font (i.e. hides font squares that serves as font loaders)
> refactor: add font-display property for oui-icons

- packages/apps/builder/.config/webpack.config.js
- packages/apps/builder/package.json
- packages/apps/builder/src/oui-flags.less
- packages/apps/builder/src/oui-icons.less
- packages/base/core/src/index.less
- packages/base/core/src/less/_variables.less
- packages/base/core/src/oui-flags.less
- packages/base/core/src/oui-icons.less
Create `oui-icons.css` and `oui-flags.css` in the `/dist` files.
So we can use them regardless of the main `oui.css`.
Since Webpack create 2 empty `.js` and `.js.map` files, they are excluded when we copy them from the builder app.
> build: add css files for icons and flags

- packages/base/config/src/webpack.dist.config.js
- packages/base/config/src/webpack.rules.js
Related to https://github.com/ovh/ovh-ui-kit-bs/pull/96
- Remove the sourcemaps generated with the `dist` files.
> build: remove sourcemap on dist files

- package.json
- packages/base/core/package.json
- yarn.lock
Related to https://github.com/ovh/ovh-ui-kit/pull/606
Since the fix has been released on `svg2ttf`, I remove the forked package of `icon-font-generator`.
`icon-font-generator` and `webfont-generator` haven't been updated yet, so I force the resolution of the version `svg2ttf@^v5.0.0`.
> build: remove forked icons generator

- packages/components/field/src/js/field.controller.js
Add more checks before using `this.form` to avoid `undefined` errors when there is no `form` wrapper
Close https://github.com/ovh/ovh-ui-kit/issues/496
> fix(field): fix errors when no form wrapper

- README.md
docs: add changelog URL
We can reach the changelog also via the `README.md` file.
It avoid to launch the GitHub Page (Storybook UI and the go on `Changelog` page.)
None.
None.
Signed-off-by: Antoine Leblanc <antoine.leblanc@ovhcloud.com>
> docs: add changelog URL

- packages/base/config/src/webpack.rules.js
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
Don't process svgs as html 
fix #696
> fix(config): prevent processing svg as html

- packages/apps/workshop/stories/design-system/components/file/file-webcomponent.stories.js
- packages/components/file/src/js/file.controller.js
- packages/components/file/src/js/file.spec.js
Fix File component error handling
Added a method to cleanup errors on file remove
Added a unit test for the issue
Fixed the Validate story, as it was not showing any sign of validation
Better user experience
A very light slow down on a performance side (only when removing a file) as we cycle through the files in the model to check if at least one of them has some error
The user has a multiple file input, he/she upload a valid file, then an invalid file (max size exceeded).
After removing the invalid file, currently, the form stay invalid (when it should become valid)
> fix(file): add error cleanup on file removal

- packages/components/field/src/js/field.provider.js
- packages/components/file/src/js/file.controller.js
- packages/components/file/src/js/file.spec.js
Fix File component extension validation
Added the file extension validation
Added a parsing for the accept attribute (to avoid validation based on incorrect values)
Added unit tests
Better user experience by adding a visual hint that a file with an invalid extension is invalid
Some light slow down on a performance side (on the component initialization and after selecting a file) as we cycle through the MIME types / extensions to parse them (component initialization) and validate input extension (file selection)
When a user select a file with an invalid extension, the error is not displayed on the file "preview" and the form is not considered as invalid.
> fix(file): added file extension validation

- packages/components/file/src/js/file.controller.js
- packages/components/file/src/js/file.spec.js
Cleanup file error when none is present
Setting up the same error management for maxsize and type errors
Added some tests to cover the Applicable Issues
Better user experience by removing an incorrect visual hint that a valid file uploaded after an invalid one is invalid
When a user select a file with an invalid extension and then a valid file, the valid file appears as invalid.
> fix(file): cleanup file error when none is present
