CONTRIBUTING.md
=> fix(contributing): remove unwanted character

CONTRIBUTING.md
=> docs(contributing): wrap signed-off-by example in code block

packages/oui-message/README.md
=> docs(oui-message): reorganize examples groups

.stylelintrc.js, packages/oui-table/README.md, packages/oui-table/_mixins.less, packages/oui-table/table.less
Signed-off-by: Caroline Zowczak <caroline.zowczak@corp.ovh.com>
=> feat(oui-table): update th arrow style

README.md, package.json, yarn.lock
=> chore(npm): add less-plugin-remcalc dependency

packages/oui-list/_mixins.less
=> fix(list): icon underlined IE

packages/oui-input/_normalize.less
=> fix(input): hide input password icon on IE

packages/oui-input/_mixins.less, packages/oui-input/_variables.less
=> fix(input): font on focus on edge

packages/oui-modal/README.md, packages/oui-modal/_mixins.less, packages/oui-modal/_variables.less
Signed-off-by: Kevin Manson <kevin.manson@corp.ovh.com>
=> feat(oui-modal): add modifier to show a modal without icon

packages/oui-button/README.md, packages/oui-button/_mixins.less, packages/oui-button/_variables.less, packages/oui-button/button.less
Signed-off-by: Caroline Zowczak <caroline.zowczak@corp.ovh.com>
=> feature(oui-button): add button-link

packages/oui-progress/README.md, packages/oui-progress/_mixins.less, packages/oui-progress/_normalize.less, packages/oui-progress/_variables.less, packages/oui-progress/progress.less, packages/oui/stylekit.less
=> feat(oui-progress): new component

yarn.lock
Signed-off-by: Antoine Leblanc <antoine.leblanc@corp.ovh.com>
=> chore(yarn): update yarn.lock file.

packages/oui-radio/_normalize.less
=> fix(oui-radio): add box-sizing property to fix radio size

packages/oui-input-group/README.md, packages/oui-input-group/_mixins.less
=> fix(oui-input-group): add example for oui-input_number modifier

.stylelintrc.js, packages/oui-button/_mixins.less, packages/oui-checkbox/_mixins.less, packages/oui-input-group/_mixins.less, packages/oui-input/_mixins.less, packages/oui-progress/_mixins.less, packages/oui-radio/_mixins.less, packages/oui-select/_mixins.less, packages/oui-switch/_mixins.less
=> fix(*): replace all 0px by 0 and add corresponding stylelint rule

.stylelintrc.js, packages/oui-checkbox/_mixins.less, packages/oui-icons/fonts.less, packages/oui-list/_mixins.less, packages/oui-progress/_mixins.less, packages/oui-progress/progress.less, packages/oui-radio/_mixins.less, packages/oui-select/_normalize.less, packages/oui-tip/_mixins.less, packages/oui-typography/fonts.less, packages/oui/_settings.less
=> Fix stylelint

packages/oui-responsive/README.md, packages/oui-responsive/_mixins.less, packages/oui-responsive/_variables.less, packages/oui-responsive/responsive.less, packages/oui-table/README.md, packages/oui-table/_mixins.less, packages/oui-table/_variables.less, packages/oui-table/table.less, packages/oui/stylekit.less
=> feat(oui-table): give responsiveness to oui-table

packages/oui-checkbox/README.md, packages/oui-checkbox/_mixins.less
=> feature(oui-checkbox): add possibility to display a checkbox without label

packages/oui-button/_variables.less
=> fix(button): fix small width padding

packages/oui-typography/_variables.less
=> fix(typography): variable depends on constants

packages/oui-input/_mixins.less, packages/oui-textarea/README.md, packages/oui-textarea/_mixins.less, packages/oui-textarea/textarea.less
Add inline modifier for textarea (as existing for select, input, and so on...)
Preview : http://dev_feature_oui_textarea_inline.ui-kit.ovh/#!/ovh-ui-kit/textarea
=> feat(oui-textarea): add inline modifier for textarea

packages/oui-field/_mixins.less
Add responsiveness to oui-field.
Preview : http://dev_fix_oui_form_responsive.ui-kit.ovh/#!/ovh-ui-kit/field
=> fix(oui-field): add responsiveness on fields

packages/oui-input-group/README.md
Button tags was closed too early...
=> fix(oui-input-group): fix documentation

packages/oui-themes/README.md, packages/oui-themes/diamond/_mixins.less, packages/oui-themes/sapphire/_mixins.less, packages/oui-themes/themes.less
=> feat(oui-themes): custom headers for diamond theme

packages/oui-themes/themes.less
=> feature(theme diamond): change line height on radios and checkboxes

packages/oui-input-group/README.md, packages/oui-input-group/_mixins.less, packages/oui-input-group/_variables.less, packages/oui-input-group/input-group.less
Demo here: http://dev_feature_oui_input_group_numeric.ui-kit.ovh/#!/ovh-ui-kit/input-group
=> feat(oui-input-group): add numeric modifier

packages/oui-list/README.md, packages/oui-list/_mixins.less, packages/oui-list/_variables.less
Demo: http://dev_feature_oui_list_item_optional.ui-kit.ovh/#!/ovh-ui-kit/list
=> feat(oui-list): new optional modifier on step list items

packages/oui-button/README.md, packages/oui-button/_mixins.less, packages/oui-button/_variables.less, packages/oui-button/button.less
Demo: http://dev_feature_button_large_height.ui-kit.ovh/#!/ovh-ui-kit/button
=> feat(button): large height button modifier

packages/oui-modal/README.md, packages/oui-modal/_mixins.less
=> Warning message icon in modal was not correctly displayed

packages/oui-list/README.md, packages/oui-list/_mixins.less, packages/oui-list/list.less
Demo: http://dev_feat_oui_list_step_checkbox.ui-kit.ovh/#!/ovh-ui-kit/list
=> feat(oui-list): support checkbox as list item

packages/oui-input-group/README.md, packages/oui-input-group/_mixins.less, packages/oui-input-group/input-group.less
=> bugfix(input-group): center numeric input text

packages/oui-field/README.md, packages/oui-field/_mixins.less
http://dev_fix_oui_field_default_width.ui-kit.ovh/#!/ovh-ui-kit/field
=> feat(field): add default size

packages/oui-modal/README.md, packages/oui-modal/_mixins.less, packages/oui-modal/_variables.less, packages/oui-modal/modal.less
Signed-off-by: Mathieu Boulianne <mathieu.boulianne@corp.ovh.com>
=> feat(oui-modal) => Add some modal icon (success, error, info, help, etc)

packages/oui-progress/README.md, packages/oui-progress/_mixins.less, packages/oui-progress/_variables.less, packages/oui-progress/progress.less
=> feat(progress): add thresholds and labels alignment

packages/oui-progress/README.md, packages/oui-progress/_mixins.less, packages/oui-progress/_variables.less
=> fix(progress): fix progress bugs and design

packages/oui-tip/_mixins.less, packages/oui-tip/_variables.less, packages/oui-tip/tip.less, packages/oui-tooltip/_mixins.less, packages/oui-tooltip/_variables.less, packages/oui-tooltip/tooltip.less, packages/oui/stylekit.less
UU-519 (linked to https://github.com/ovh-ux/ovh-ui-angular/pull/21)
Preview http://temp_oui_tooltip.ui-kit.ovh
=> feat(oui-tooltip): add oui-tooltip component

packages/oui-input-group/_mixins.less
=> fix(oui-input-group): support primary and secondary buttons

packages/oui-button/_mixins.less, packages/oui-button/_variables.less, packages/oui-button/button.less
http://dev_fix_button_padding.ui-kit.ovh/#!/ovh-ui-kit/button
Only horizontal paddings have been changed (left and right). Main changes are on buttons with icons.
=> fix(oui-button): new padding with icons

packages/oui-navbar/README.md, packages/oui-navbar/_mixins.less, packages/oui-navbar/_variables.less, packages/oui-navbar/navbar.less, packages/oui-responsive/README.md, packages/oui-responsive/_mixins.less
UU-532
Staging: http://feature_oui_navbar.ui-kit.ovh (main navbar)
http://feature_oui_navbar.ui-kit.ovh/#!/ovh-ui-kit/navbar
=> feat(oui-navbar): update oui-navbar to new specs

packages/oui-navbar/_mixins.less, packages/oui-navbar/navbar.less
=> fix(eslint): disable indentation fails

packages/oui-tooltip/_mixins.less, packages/oui-tooltip/_normalize.less, packages/oui-tooltip/_variables.less, packages/oui-tooltip/tooltip.less
UU-558
Linked to https://github.com/ovh-ux/ovh-ui-angular/pull/35
Staging: http://build_oui_tooltip.ui-kit.ovh/#!/oui-angular/tooltip
=> style(oui-tooltip): update oui-tooltip to specs

packages/oui-pagination/README.md, packages/oui-pagination/_mixins.less, packages/oui-pagination/_variables.less, packages/oui-pagination/pagination.less, packages/oui-responsive/_mixins.less, packages/oui/stylekit.less
Staging: http://dev_oui_pagination.ui-kit.ovh/#!/ovh-ui-kit/pagination
=> ouiPagination component

packages/oui-action-menu/_variables.less
Preview: http://dev_fix_oui_action_menu_hover_color.ui-kit.ovh/#!/oui-angular/action-menu
=> fix(ouiActionMenu): fix menu-item hover colors

CHANGELOG.md
=> doc(changelog): create a new file

packages/oui-datagrid/_mixins.less
=> fix(datagrid): remove animation on rows to avoid spinner displaying issue

package.json
=> feat(build): add dist's files on preversion

packages/oui-datagrid/_mixins.less
=> fix(datagrid): remove pointer cursor on unsortable column headers

packages/oui-button/_mixins.less, packages/oui-navbar/README.md, packages/oui-navbar/_mixins.less, packages/oui-navbar/_variables.less, packages/oui-navbar/navbar.less
Related
https://github.com/ovh-ux/ovh-ui-angular/pull/63
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/46
Staging: http://build_oui_navbar.ui-kit.ovh/#!/ovh-ui-kit/navbar
=> style(oui-navbar): update style for oui-navbar component

package.json, packages/oui-icons/fonts.less, packages/oui-responsive/_mixins.less, packages/oui/_settings.less
=> fix(icons): add version of ovh-ui-kit in @font-face src

packages/oui-navbar/_mixins.less, packages/oui-navbar/_variables.less, packages/oui-navbar/navbar.less, packages/oui-responsive/README.md, packages/oui-responsive/_mixins.less, packages/oui-responsive/_variables.less
Linked with https://github.com/ovh-ux/ovh-ui-angular/pull/82
=> fix(navbar): fix transition slide and add a breakpoint for responsive

package.json, packages/oui-checkbox/_mixins.less, packages/oui-icons/_mixins.less, packages/oui-radio/_mixins.less, yarn.lock
=> chore(): upgrade packages

packages/oui-action-menu/_mixins.less
=> fix(action-menu): fix text color of disabled items

packages/oui-datagrid/_mixins.less
Signed-off-by: Kevin Manson kevin.manson@corp.ovh.com
=> fix(datagrid): remove relative position in datagrid cells

packages/oui-navbar/_mixins.less, packages/oui-navbar/_variables.less
=> style(navbar): update colors for menu items

packages/oui-modal/README.md, packages/oui-modal/_mixins.less, packages/oui-modal/_variables.less, packages/oui-modal/modal.less
=> fix(modal): fix shadow color

packages/oui-button/_mixins.less, packages/oui-button/_variables.less, packages/oui-ui-select/_mixins.less, packages/oui-ui-select/_normalize.less, packages/oui-ui-select/_variables.less, packages/oui-ui-select/ui-select.less, packages/oui/stylekit.less
=> feat(ui-select): add styles for ui-select

packages/oui-textarea/README.md, packages/oui-textarea/_mixins.less, packages/oui-textarea/_variables.less, packages/oui-textarea/textarea.less
=> feat(textarea): add new component

packages/oui-button/_mixins.less, packages/oui-button/_variables.less, packages/oui-field/_mixins.less, packages/oui-field/field.less, packages/oui-textarea/_mixins.less, packages/oui-textarea/_variables.less, packages/oui-textarea/textarea.less, packages/oui-ui-select/_mixins.less, packages/oui-ui-select/_variables.less
=> Oui field textarea

packages/oui-textarea/_mixins.less
=> fix(ouiTextarea): add resize handle to textarea

packages/oui-input-group/_mixins.less, packages/oui-input-group/_variables.less, packages/oui-input-group/input-group.less, packages/oui-input/README.md, packages/oui-input/_mixins.less, packages/oui-input/_variables.less
UU-568
http://build_oui_search.ui-kit.ovh/#!/oui-angular/search
Linked to
https://github.com/ovh-ux/ovh-ui-angular/pull/105
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/61
=> style(oui-search): add variant oui-input-group-search

.scriptsrc, CHANGELOG.md, CONTRIBUTING.md, commitlint.config.js, package.json, yarn.lock
*note:* commit messages scope need to be a component name, but is optional (based on folders)
=> chore: commitlint, commitizen and conventional-changelog integration

packages/oui-criteria-adder/criteria-adder.less, packages/oui-ui-select/_mixins.less, packages/oui/stylekit.less
UU-744
http://build_oui_criteria_adder.ui-kit.ovh/#!/oui-angular/criteria-adder
The icon of the dropdown button is temporary. 
It'll be replaced when I'll receive the good one.
Related to
https://github.com/ovh-ux/ovh-ui-angular/pull/115
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/68
=> style(oui-criteria-adder): add criteria adder style

packages/oui-chip/README.md, packages/oui-chip/_normalize.less, packages/oui-chip/_variables.less, packages/oui-chip/chip.less, packages/oui/stylekit.less
UU-727
http://build_oui_chips.ui-kit.ovh/#!/ovh-ui-kit/chip
Related to:
https://github.com/ovh-ux/ovh-ui-angular/pull/122
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/69
=> feat(oui-chip): add chip component style

packages/oui-field/_mixins.less, packages/oui-input/_mixins.less
Staging: https://ovh_ui_kit_documentation-fix_form_submit_staging.uxci.ovh/#!/oui-angular/field
=> style(oui-field): add error style for oui-input

packages/oui-button/_variables.less
=> fix(oui-back-button): fix arrow color to be the same as a link

package.json, packages/oui-calendar/_normalize.less, packages/oui-calendar/calendar.less, packages/oui/_settings.less, packages/oui/stylekit.less, yarn.lock
UU-562
http://build_oui_calendar.ui-kit.ovh/#!/oui-angular/calendar
Related to
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/77
https://github.com/ovh-ux/ovh-ui-angular/pull/128
=> feat(oui-calendar): add styles for oui-calendar component

package.json, packages/oui-calendar/_normalize.less, yarn.lock
https://github.com/ovh-ux/ovh-ui-angular/pull/142
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/78
=> chore(oui-calendar): remove flatpickr import

package.json, packages/oui-calendar/_normalize.less, packages/oui-calendar/_variables.less, packages/oui-calendar/calendar.less, packages/oui-input/_mixins.less
UU-778
* Bump flatpickr to v4.4.3
* Update calendar style to specs
http://build_oui_field_calendar.ui-kit.ovh/#!/oui-angular/calendar
http://build_oui_field_calendar.ui-kit.ovh/#!/oui-angular/field
**Linked to**
https://github.com/ovh-ux/ovh-ui-angular/pull/146
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/83
=> feat(oui-calendar): update calendar style to specs

packages/oui-popover/README.md, packages/oui-popover/_normalize.less, packages/oui-popover/_variables.less, packages/oui-popover/popover.less, packages/oui/stylekit.less
=> feat(oui-popover): add new Popover component styles

packages/oui-status/README.md, packages/oui-status/_normalize.less, packages/oui-status/status.less, packages/oui/stylekit.less
=> feat(oui-status): add new oui-status

packages/oui-ui-select/_mixins.less
Demo: http://fix_oui_select_dropdown_width_staging.ui-kit.ovh/#!/oui-angular/select
=> fix(oui-select): fix dropdown min-width

packages/oui-textarea/README.md, packages/oui-textarea/_mixins.less, packages/oui-textarea/textarea.less
Demo: http://dev_fix_oui_textarea_disabled.ui-kit.ovh/#!/ovh-ui-kit/textarea
Demo is not presented but check if it don't break simple cases.
=> fix(oui-textarea): fix disable state in fieldset

packages/oui-textarea/_mixins.less
Fix this issue https://github.com/ovh-ux/ovh-ui-kit/issues/185
=> fix(oui-textarea): fix slow resizing

packages/oui-navbar/_mixins.less, packages/oui-navbar/_variables.less
Linked to
https://github.com/ovh-ux/ovh-ui-angular/pull/183
https://github.com/ovh-ux/ovh-documentation-toolkit/pull/27
=> style(oui-navbar): add style for brand title

packages/oui-icons/README.md, packages/oui-navbar/_variables.less, packages/oui-navbar/navbar.less, packages/oui-radio-toggle-group/radio-toggle-group.less
- show a message when no notification or when something went wong
- avoid wraping phrases in radio-toggle-group
=> feat(oui-navbar): add placeholder for notification

packages/oui-page-header/README.md, packages/oui-page-header/_normalize.less, packages/oui-page-header/_variables.less, packages/oui-page-header/page-header.less, packages/oui/stylekit.less
`/#!/ovh-ui-kit/page-header` @ `ovh_ui_kit_documentation-feat_page_header_staging`
**Linked to**
https://github.com/ovh-ux/ovh-ui-angular/pull/204
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/119
=>  feat(oui-page-header): create style

packages/oui-tile/README.md, packages/oui-tile/_normalize.less, packages/oui-tile/_variables.less, packages/oui-tile/tile.less, packages/oui/stylekit.less
migrate ui-kit-bs tile style
add README with 3 concrete examples
=> feat(oui-tile): create component

packages/oui-header-tabs/header-tabs.less
`/#!/ovh-ui-angular/header-tabs` @ `ovh_ui_kit_documentation-feat_header_tabs_staging`
**Linked to**
https://github.com/ovh-ux/ovh-ui-angular/pull/217
=> refactor(oui-header-tabs): add disabled flag on items

packages/oui-tile/tile.less
Linked to
https://github.com/ovh-ux/ovh-ui-angular/pull/219
=> style(oui-tile): center spinner

packages/oui-typography/README.md, packages/oui-typography/typography.less
http://dev_feature_abbr_style.ui-kit.ovh/
=> feat(oui-typography): add abbr style from specs

packages/oui-tile/_normalize.less, packages/oui-tile/tile.less
UK-40
Linked to 
https://github.com/ovh-ux/ovh-ui-angular/pull/221
=> fix(oui-tile): fix normalize for height sizing

packages/oui-field/_mixins.less, packages/oui-field/field.less, packages/oui-switch/README.md, packages/oui-switch/_mixins.less, packages/oui-switch/_variables.less, packages/oui-switch/switch.less
/#!/ovh-ui-angular/switch @ ovh_ui_kit_documentation-feat_oui_switch_staging
Linked to
https://github.com/ovh-ux/ovh-ui-angular/pull/191
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/125
=> feat(oui-switch): add new oui-switch styles

packages/oui-popover/popover.less
Linked to https://github.com/ovh-ux/ovh-ui-angular/pull/229
=> fix(oui-popover): update style to specs

packages/oui-button/_mixins.less, packages/oui-button/button.less, packages/oui-tile/tile.less
=> feat(oui-tile): handle icon for external link in tile button

packages/oui-navbar/_mixins.less, packages/oui-navbar/_normalize.less, packages/oui-navbar/_variables.less, packages/oui-navbar/navbar.less, packages/oui-switch/_variables.less, packages/oui-tooltip/_mixins.less, packages/oui-tooltip/tooltip.less
http://build_upgrade_navbar.ui-kit.ovh/#!/oui-angular/navbar
- Remove useless mixins
- Add normalize style for custom tags
- Update selectors to support new navbar components
Linked to https://github.com/ovh-ux/ovh-ui-angular/pull/235
=> feat(oui-navbar): add new components

packages/oui-button/button.less, packages/oui-tile/tile.less
http://build_tile_button_disabled.ui-kit.ovh/#!/oui-angular/tile
Linked to https://github.com/ovh-ux/ovh-ui-angular/pull/237
=> feat(oui-tile): add disabled on oui-tile-button

package.json, packages/oui-checkbox/_mixins.less, packages/oui-checkbox/_variables.less, packages/oui-criteria-adder/criteria-adder.less, packages/oui-datagrid/_mixins.less, packages/oui-datagrid/_variables.less, packages/oui-datagrid/datagrid.less, packages/oui-icons/icons.less, packages/oui-radio/_mixins.less, packages/oui-select/_mixins.less, packages/oui/_settings.less, yarn.lock
* Update dependencies for LESS v3
* Fix Radio style
* Fix Checkbox style
* Fix Criteria style
=> fix: fix for LESS v3

packages/oui-tile/tile.less, packages/oui-typography/typography.less
=> fix(oui-tile): normal word break for oui-paragraph

packages/oui-navbar/navbar.less, packages/oui-sidebar/README.md, packages/oui-sidebar/_variables.less, packages/oui-sidebar/sidebar.less, packages/oui/stylekit.less
- Add style for oui-sidebar
- Add examples for oui-sidebar documentation
Linked to https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/143
=> feat(oui-sidebar): add sidebar style

packages/oui-status/status.less, packages/oui-typography/_variables.less, packages/oui-typography/typography.less, packages/oui/_reboot.less, packages/oui/_settings.less, packages/oui/stylekit.less
Add reboot style forked from BS4 for the base elements
=> fix: fix reboot style

packages/oui/_settings.less
* Fix margin for those controls when used in `oui-field`
=> fix: add missing form controls

packages/oui-typography/_mixins.less, packages/oui-typography/typography.less
* fix margin auto on `hr`
* remove useless mixins
=> style(oui-typography): remove useless mixins

packages/oui-message/_mixins.less, packages/oui-modal/_mixins.less, packages/oui-popover/_normalize.less, packages/oui-popover/_variables.less, packages/oui-popover/popover.less
UK-55
* Add animation on opening / closing
* Clean unused style from refactoring
Related to:
* https://github.com/ovh-ux/ovh-ui-angular/pull/301
=> feat(oui-popover): add animation on opening

packages/oui-calendar/_normalize.less, packages/oui-calendar/_variables.less
UK-66
* Update header style to specs
* Update timepicker style to specs
Related to https://github.com/ovh-ux/ovh-ui-angular/pull/302
=> style(oui-calendar): update timepicker style to specs

packages/oui-field/_mixins.less, packages/oui-inline-adder/_normalize.less, packages/oui-inline-adder/inline-adder.less, packages/oui/stylekit.less
UK-16
Related to
https://github.com/ovh-ux/ovh-ui-angular/pull/304
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/168
=> feat(oui-inline-adder): add inline-adder component

packages/oui-animation/_variables.less, packages/oui-icons/README.md, packages/oui-icons/icons.less
Add CSS selector to shake icon
=> feat(oui-icons): add icon shaking animation

packages/oui-button/_mixins.less, packages/oui-collapsible/collapsible.less, packages/oui-dual-list/_normalize.less, packages/oui-dual-list/_variables.less, packages/oui-dual-list/dual-list.less, packages/oui/stylekit.less
UK-15
Related to
https://github.com/ovh-ux/ovh-ui-angular/pull/311
https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/171
=> feat(oui-dual-list): add dual-list component

packages/oui-autocomplete/autocomplete.less, packages/oui-dropdown/_variables.less, packages/oui/stylekit.less
UK-59
Related to
* https://github.com/ovh-ux/ovh-ui-angular/pull/315
* https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/172
=> feat(oui-autocomplete): add autocomplete directive

packages/oui-tabs/_normalize.less, packages/oui-tabs/_variables.less, packages/oui-tabs/tabs.less, packages/oui/stylekit.less
UK-62
Related to
* https://github.com/ovh-ux/ovh-ui-angular/pull/319
* https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/173
=> feat(oui-tabs): add tabs component

package.json, packages/oui/_dist.less
Quick fix to update path of icons in builded dist files.
=> fix(oui-icons): fix dist icons path

packages/oui-file/_normalize.less, packages/oui-file/_variables.less, packages/oui-file/file.less, packages/oui/_settings.less, packages/oui/stylekit.less
UK-60
Related to
* https://github.com/ovh-ux/ovh-ui-angular/pull/324
* https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/174
=> feat(oui-file): add file component

packages/oui-field/_mixins.less, packages/oui-field/field.less, packages/oui-select-picker/_mixins.less, packages/oui-select/_mixins.less, packages/oui-select/_variables.less, packages/oui-ui-select/_mixins.less, packages/oui-ui-select/_normalize.less, packages/oui-ui-select/_variables.less, packages/oui-ui-select/ui-select.less
UK-64
Related to
* https://github.com/ovh-ux/ovh-ui-angular/pull/327
=> refactor(oui-select): use ui-select in a proper way

packages/oui-navbar/_variables.less, packages/oui-navbar/navbar.less
=> fix(oui-navbar): have menu items have own line height

packages/oui-chip/_variables.less, packages/oui-chip/chip.less, packages/oui-ui-select/_variables.less, packages/oui-ui-select/ui-select.less
UK-65
Related to https://github.com/ovh-ux/ovh-ui-angular/pull/332
=> feat(oui-select): add multiple selection

packages/oui-calendar/_normalize.less, packages/oui-calendar/_variables.less, packages/oui-timepicker/_normalize.less, packages/oui-timepicker/timepicker.less, packages/oui/stylekit.less
UK-61
Related to:
* https://github.com/ovh-ux/ovh-ui-angular/pull/344
* https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/179
=> feat(oui-timepicker): add timepicker component

packages/oui-progress-tracker/_variables.less, packages/oui-progress-tracker/progress-tracker.less
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
addErrorStateOnTrackerProgress
Add error style for progress-tracker
We can use an error state to view steps in error on a tracker
=> feat: add class error into progress-tracker

packages/oui-skeleton/_normalize.less, packages/oui-skeleton/skeleton.less
=> fix(oui-skeleton): apply class immediately

packages/oui-spinner/README.md
style(readme): typo on 'Medium'
There's a typo on "Medum" => "Medium"
=> style(readme): typo on 'Medium'

packages/oui-pagination/pagination.less
**Related to**
- https://github.com/ovh-ux/ovh-ui-angular/pull/358
- https://github.com/ovh-ux/ovh-ui-kit-documentation/pull/183
=> fix(oui-pagination): add input search when huge amount of pages

packages/apps/workshop/stories/components/criteria.stories.js
043e06e - docs(apps.workshop.stories.components.criteria): remove typo
Note: This pull request targets `master` branch due the lack of synchronisation between `develop` and `master` branch.
=> docs(apps.workshop.stories.components.criteria): remove typo

packages/oui-navbar/navbar.less
=> feat(oui-navbar): add style for menu header container

packages/apps/workshop/stories/components/tabs.stories.js, packages/components/tabs/README.md, packages/components/tabs/package.json, packages/components/tabs/src/js/item/tabs-item.controller.js, packages/components/tabs/src/js/tabs.component.js, packages/components/tabs/src/js/tabs.controller.js, packages/components/tabs/src/js/tabs.html, packages/components/tabs/src/js/tabs.spec.js
49c6315 - feat(tabs): allow to select active tab item
- No QC required.
ref: https://github.com/ovh-ux/ovh-ui-angular/pull/398
=> feat(tabs): allow to select active tab item

packages/components/navbar/src/js/menu/navbar-menu.component.js, packages/components/navbar/src/js/menu/navbar-menu.controller.js, packages/components/navbar/src/js/menu/navbar-menu.html, packages/components/navbar/src/js/navbar.html, packages/components/navbar/src/js/navbar.spec.js, packages/components/navbar/src/js/toggler/navbar-toggler.component.js, packages/components/navbar/src/js/toggler/navbar-toggler.html, packages/components/navbar/src/less/navbar.less
8937886 - feat(navbar): add style for menu header container
- No QC required.
ref: #394
=> feat(navbar): add style for menu header container

packages/components/stepper/README.md, packages/components/stepper/src/js/step-form/step-form.controller.js
da09735 - feat(stepper): emit event on form submit
- No QC required.
ref: https://github.com/ovh-ux/ovh-ui-angular/pull/402
=> feat(stepper): emit event on form submit

packages/oui-dropdown/dropdown.less
Add arrows when dropdown is positioned on the left/right
https://github.com/ovh-ux/ovh-ui-angular/pull/403
=> feat(oui-dropdown): add arrow styles for left and right  placement

packages/oui-icons/README.md, packages/oui-icons/svg/search_extra-thin.svg
=> feat(oui-icons): add extra thin search icon

packages/apps/workshop/stories/content/icons.stories.js
1ff3396 - style(apps.workshop.stories.content): remove extra space on icon story
=> style(apps.workshop.stories.content): remove extra space on icon story

packages/oui-dropdown/dropdown.less
=> fix(oui-dropdown): fix arrow position for side placement

packages/base/core/src/less/mixins/choice.less
Replicate https://github.com/ovh-ux/ovh-ui-kit/pull/425
=> fix(oui-checkbox): add relative position

.stylelintrc.json, packages/base/core/package.json, packages/base/core/src/css/_tokens.css, packages/base/core/src/js/download-tokens.js
- Fix typo
- Add download script of the CSS tokens
=> build: add css tokens download script

packages/apps/workshop/stories/components/tabs.stories.js, packages/base/core/src/less/mixins/accessibility.less, packages/components/tabs/src/js/tabs.controller.js
Since https://github.com/ovh-ux/ovh-ui-kit/pull/398, tab doesn't open content on click.
It's visible here: https://ovh-ux.github.io/ovh-ui-kit/?path=/story/components-tabs--simple
In the same time, I've cleaned the story and fixed a bad animation when a tab is focused.
=> fix(tabs): fix tabs that won't open on click

packages/oui-file/_variables.less, packages/oui-file/file.less
Prevent large list display if many files are added
=> feat(oui-file): add max-height to file list

packages/apps/workshop/stories/components/stepper.stories.js, packages/components/stepper/src/js/step-form/step-form.html
Show the 'modify step' button even when the previous steps aren't submitted.
=> fix(stepper): fix modify step button appearance

packages/components/dropdown/README.md, packages/components/header/README.md, packages/components/navbar/README.md, packages/libs/ui-kit/package.json
- Add missing peer dependencies
- Update docs about @uirouter/angularjs
=> build: add missing peer dependencies

.gitignore, packages/apps/workshop/stories/components/datagrid.stories.js, packages/base/core/src/less/_variables.less, packages/components/datagrid/README.md, packages/components/datagrid/src/index.js, packages/components/datagrid/src/js/datagrid.controller.js, packages/components/datagrid/src/js/datagrid.html, packages/components/datagrid/src/js/datagrid.spec.js, packages/components/datagrid/src/js/row-detail/datagrid-row-detail.component.js, packages/components/datagrid/src/js/row-detail/datagrid-row-detail.controller.js, packages/components/datagrid/src/less/datagrid.less
31d0b38 - add expandable row detail
Add the possibility to add detail for each row of the dataset.
The row detail will make the row expandable to show details of it.
This feature is based on the work made on this PR : https://github.com/ovh-ux/ovh-ui-kit/pull/403
=> feat(oui-datagrid): add expandable row detail

packages/oui-button/_mixins.less
https://github.com/ovh-ux/ovh-ui-kit/pull/471/files#diff-886a4ca020ffd7cdbb58ab6640bfdf4cL388
⚠️ This is a breaking change but I mean ¯\\_(ツ)_/¯
=> fix(oui-button): remove full height when setting full width

packages/apps/workshop/stories/_data/criteria.data.json, packages/components/criteria/README.md, packages/components/criteria/src/js/adder/criteria-adder.html, packages/components/criteria/src/js/adder/criteria-adder.spec.data.json, packages/components/criteria/src/js/adder/criteria-adder.spec.js
- Add support of `hideOperators` property
- Update unit tests
- Update documentation
=> feat(criteria): add ability to hide operators field

packages/base/core/src/less/_variables.less
fix(eslint): error on fade function
A typo was existing in the variables file :)
=> fix(eslint): error on fade function

packages/apps/workshop/stories/components/checkbox.stories.js, packages/apps/workshop/stories/components/radio.stories.js, packages/base/core/src/less/_variables.less, packages/components/checkbox/README.md, packages/components/checkbox/src/js/checkbox.component.js, packages/components/checkbox/src/js/checkbox.html, packages/components/checkbox/src/js/checkbox.spec.js, packages/components/checkbox/src/less/_mixins.less, packages/components/checkbox/src/less/checkbox.less, packages/components/radio/README.md, packages/components/radio/src/js/radio.component.js, packages/components/radio/src/js/radio.html, packages/components/radio/src/js/radio.spec.js, packages/components/radio/src/less/_mixins.less
feat(radio&checkbox): add ability to display a footer when in thumbnail mode
* Add support of `footer` property
* Update unit tests
* Update documentation
Add an extra section in all thumbnail-mode radios & checkboxes
=> feat(radio&checkbox): add ability to display a footer when in thumbnail mode

packages/apps/workshop/stories/components/stepper.stories.js, packages/components/stepper/src/js/step-form/step-form.controller.js, packages/components/stepper/src/js/stepper.controller.js, packages/components/stepper/src/less/stepper.less
=> fix(stepper): fix onFocus callback launched multiple times

packages/components/dropdown/src/js/item/dropdown-item.html
=> fix(oui-dropdown): display button when item has href and is disabled

packages/components/dropdown/README.md, packages/components/dropdown/src/js/item/dropdown-item.html
Backport of the following PR : https://github.com/ovh-ux/ovh-ui-angular/pull/427
=> fix(oui-dropdown): remove one time binding of href attribute

packages/components/navbar/README.md, packages/components/navbar/src/js/menu/navbar-menu.component.js, packages/components/navbar/src/js/menu/navbar-menu.html, packages/components/navbar/src/js/navbar.spec.js
Replicate changes made : https://github.com/ovh-ux/ovh-ui-angular/pull/429
=> feat(oui-navbar): allow to create link as menu header

packages/apps/workshop/.storybook/webpack.config.js, packages/base/config/package.json, packages/base/config/src/webpack.rules.js, yarn.lock
Fix Edge compatibility when using spread operator on objects: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility
=> build: fix object spread operator compatibility on edge

packages/apps/workshop/stories/components/box.stories.js, packages/base/core/src/less/_variables.less, packages/components/box/src/less/box.less
feat(box): modify style
Modify style of current oui-box
=> feat(box): apply ODS theme

packages/oui-select-picker/_mixins.less, packages/oui-select-picker/_variables.less
Apply https://github.com/ovh-ux/ovh-ui-kit/pull/518 to v2.x
=> feat(oui-select-picker) add footer and picture transclude

packages/apps/workshop/stories/content/typography.stories.js, packages/base/core/src/less/_variables.less, packages/base/core/src/less/typography.less
ref: UK-117
Add `oui-description` class with its horizontal variant
=> feat(typography): add description horizontal

packages/oui-typography/_variables.less, packages/oui-typography/typography.less
=> feat(oui-typography): backport description horizontal

packages/oui-header-tabs/_normalize.less, packages/oui-header-tabs/_variables.less, packages/oui-header-tabs/header-tabs.less
Related to https://github.com/ovh-ux/ovh-ui-angular/pull/432
Updated with styles from v3.x that fixed this issue.
=> fix(oui-header-tabs): fix style of active item

packages/oui-criteria-adder/criteria-adder.less
update display to add elements
=> feat(oui-criteria-adder): update display to add elements

packages/components/criteria/README.md, packages/components/criteria/src/js/adder/criteria-adder.html, packages/components/criteria/src/js/adder/criteria-adder.provider.js, packages/components/criteria/src/js/adder/criteria-adder.spec.js
Replicate of https://github.com/ovh-ux/ovh-ui-angular/pull/435
=> feat(oui-criteria-adder): add button description

packages/components/calendar/src/js/calendar.controller.js
=> fix(calendar): dynamic changes for min and max date

packages/base/core/src/js/component-utils.js, packages/components/collapsible/src/js/collapsible.controller.js, packages/components/collapsible/src/js/collapsible.html
=> fix(collapsible): add helper to remove html on heading

packages/apps/workshop/stories/components/radio.stories.js, packages/base/core/src/less/_variables.less, packages/components/radio/README.md, packages/components/radio/src/js/toggle-group/radio-toggle-group.component.js, packages/components/radio/src/less/radio-toggle-group.less
Add attribute `direction` to choose between `row` (default) or `column`
ref: UK-125
=> feat(radio-toggle-group): add column direction

packages/oui-radio-toggle-group/radio-toggle-group.less
=> feat(oui-radio-toggle-group): add column direction

packages/oui-collapsible/collapsible.less
* Add `loading` attribute
* Add `group` attribute
* Update documentation
* Update unit tests
ref: UK-122
=> Feat/collapsible loading v2.x

packages/base/core/src/less/_variables.less, packages/components/calendar/README.md, packages/components/calendar/package.json, packages/components/calendar/src/js/calendar.provider.js, packages/components/calendar/src/less/flatpickr.less, packages/components/timepicker/package.json, packages/libs/ui-kit/package.json, yarn.lock
=> fix(calendar): support flatpickr v4.6.3

packages/oui-datagrid/datagrid.less
add component support to refresh Datagrid
MANAGER-4342
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
=> feat(oui-datagrid): refresh datagrid

packages/oui-navbar/_mixins.less, packages/oui-navbar/navbar.less
- Update style for `oui-navbar-menu_panel`
related to: https://github.com/ovh-ux/ovh-ui-angular/pull/459
ref: UK-148
=> feat(oui-navbar): add variant attribute on menu

.stylelintrc.json, packages/apps/workshop/stories/components/navbar.stories.js, packages/components/button/src/less/button.less, packages/components/calendar/src/less/flatpickr.less, packages/components/checkbox/src/less/checkbox.less, packages/components/header/src/less/header-tabs.less, packages/components/input/src/less/input-group.less, packages/components/list/src/less/list.less, packages/components/navbar/README.md, packages/components/navbar/src/js/menu/navbar-menu.component.js, packages/components/navbar/src/js/menu/navbar-menu.controller.js, packages/components/navbar/src/js/menu/navbar-menu.html, packages/components/navbar/src/js/navbar.spec.js, packages/components/navbar/src/js/notification/navbar-notification.component.js, packages/components/navbar/src/js/notification/navbar-notification.controller.js, packages/components/navbar/src/less/_mixins.less, packages/components/navbar/src/less/navbar.less, packages/components/progress-tracker/src/less/progress-tracker.less, packages/components/radio/src/less/radio-toggle-group.less, packages/components/radio/src/less/radio.less, packages/components/select-picker/src/less/select-picker.less, packages/components/select/src/less/_mixins.less, packages/components/select/src/less/select.less, packages/components/sidebar/src/less/sidebar.less, packages/components/switch/src/less/switch.less
- Add a `variant` attribute onto `oui-navbar-menu` and `oui-navbar-notification`
- Update documentation
- Update unit tests
ref: UK-148
=> feat(navbar): add variant attribute onto menus

packages/components/datagrid/src/js/paging/datagrid-paging-abstract.js
Backport of https://github.com/ovh-ux/ovh-ui-angular/pull/457
Close https://github.com/ovh-ux/ovh-ui-kit/issues/554
=> fix(datagrid): always call row-loader

packages/components/select-picker/src/js/select-picker.component.js, packages/components/select-picker/src/js/select-picker.html
Signed-off-by: Jérémy De-Cesare <jeremy.de-cesare@corp.ovh.com>
Backport of https://github.com/ovh-ux/ovh-ui-angular/pull/460
=> feat(oui-select-picker): add transclusion for label

packages/components/select/src/js/select.controller.js, packages/components/select/src/js/select.html, packages/components/select/src/js/select.spec.js
Replication of https://github.com/ovh-ux/ovh-ui-angular/pull/461
=> fix(oui-select): trigger onChange when element is removed

packages/apps/workshop/stories/design-system/components/textarea-webcomponent.stories.js
- remove extra `maxlength` attribute.
- remove unused `onChange` action.
- Add `onChange` attribute to the `WithMaxlength` story.
Stories are now more clear, more focused on their changes and doesn't rely on extra stories.  
None.
None.
=> Documentation - Textarea

AUTHORS, CONTRIBUTING.md, CONTRIBUTORS, MAINTAINERS, README.md
cc6e5b0 - Add AUTHORS file
1a743bf - Add CONTRIBUTORS file
1d96ec1 - Add MAINTAINERS file
2ef0325 - Update CONTRIBUTING.md file
c3996aa - docs: update README.md file
List all CONTRIBUTORS.
List all MAINTAINERS.
None.
None.
=> Minor enhancements

packages/apps/workshop/stories/design-system/components/progress-native.stories.js, packages/apps/workshop/stories/design-system/components/progress-webcomponent.stories.js, packages/base/core/src/less/variables/components/progress.less, packages/components/progress/src/less/progress.less
=> feat(progress): apply ODS theme

packages/apps/workshop/stories/design-system/components/message-native.stories.js, packages/apps/workshop/stories/design-system/components/message-webcomponent.stories.js, packages/apps/workshop/stories/legacy/components/message-native.stories.js, packages/base/core/src/less/variables/components/message.less, packages/components/message/src/less/_mixins.less, packages/components/message/src/less/message.less
- Apply ODS theme
- Fix large variant style (not supported by ODS for the moment)
Concerning the `large` variant, it'll be changed when there will be UI specs.
The examples stay in `Legacy` stories group, for now.
ref. UK-137
=> feat(message): apply ODS theme

packages/apps/workshop/stories/design-system/components/clipboard-webcomponent.stories.js, packages/base/core/src/less/_variables.less, packages/base/core/src/less/variables/components/clipboard.less, packages/base/core/src/less/variables/content/links.less, packages/components/clipboard/src/less/clipboard.less
- Apply ODS theme (Most of the changes are [here](https://github.com/ovh-ux/ovh-ui-kit/pull/583))
- Update documentation
ref. UK-135
=> feat(clipboard): apply ODS theme 

README.md, packages/libs/ui-kit/CHANGELOG.md, packages/libs/ui-kit/README.md, packages/libs/ui-kit/package.json
=> docs: replace ovh-ux by ovh in repository path

packages/apps/workshop/stories/design-system/components/password-webcomponent.stories.js, packages/base/core/src/less/variables/components/field.less, packages/base/core/src/less/variables/components/password.less, packages/components/field/src/less/field.less, packages/components/password/src/js/password.controller.js, packages/components/password/src/js/password.html, packages/components/password/src/js/strength/password-strength.html, packages/components/password/src/less/password.less
- Apply ODS theme
- Fix some styles on `oui-field`
ref. UK-139
=> feat(password): apply ODS theme

packages/apps/workshop/stories/design-system/components/file-webcomponent.stories.js, packages/base/core/src/less/mixins/forms.less, packages/base/core/src/less/typography.less, packages/base/core/src/less/variables/components/file.less, packages/components/file/README.md, packages/components/file/src/js/file.controller.js, packages/components/file/src/js/file.html, packages/components/file/src/js/file.provider.js, packages/components/file/src/less/file.less
- Apply ODS theme
- Add translation for the file placeholder in the provider
ref. UK-136
=> feat(file): apply ODS theme

packages/oui-datagrid/datagrid.less, packages/oui-tooltip/_variables.less, packages/oui-tooltip/tooltip.less
- Add tooltip on datagrid parameters
- Fix tooltip styles
ref. UK-153
=> feat(oui-datagrid): add tooltip on datagrid parameters

packages/components/datagrid/package.json, packages/components/datagrid/src/index.js, packages/components/datagrid/src/js/datagrid.html, packages/components/datagrid/src/js/datagrid.provider.js
Backport of https://github.com/ovh-ux/ovh-ui-angular/pull/462
=> feat(datagrid): add tooltip on parameters

packages/components/navbar/src/less/navbar.less
Fix the issue in Safari about shrinked notifications
=> fix(navbar): fix notifications shrink issue

packages/ovhcloud-light-theme/components/_button.less, packages/ovhcloud-light-theme/components/_datagrid.less, packages/ovhcloud-light-theme/components/_file.less, packages/ovhcloud-light-theme/components/_input.less, packages/ovhcloud-light-theme/components/_select.less, packages/ovhcloud-light-theme/index.less
- Fix some component style
- Add style for `datagrid`, `input-group` and `select`
=> fix: update ovhcloud light theme

packages/base/core/src/less/variables/components/action-menu.less, packages/base/core/src/less/variables/components/button.less, packages/base/core/src/less/variables/components/calendar.less, packages/base/core/src/less/variables/components/message.less, packages/base/core/src/less/variables/components/pagination.less, packages/base/core/src/less/variables/components/password.less, packages/base/core/src/less/variables/components/popover.less, packages/components/action-menu/src/less/action-menu.less, packages/components/button/src/less/_mixins.less, packages/components/button/src/less/button.less, packages/components/calendar/src/less/flatpickr.less, packages/components/file/src/less/file.less, packages/components/message/src/less/message.less, packages/components/password/src/less/password.less, packages/components/popover/src/less/popover.less
Some little feedbacks and fixes that was spotted during the quality check
Fix #UK-158
=> fix: fix qc feedbacks

packages/base/core/src/less/variables/components/popover.less
Use the right variable for the outline calculation
=> refactor(popover): update outline variable

packages/base/core/src/less/variables/components/tile.less, packages/components/tile/src/less/tile.less
- Update button color
- Fix buttons overflow
=> fix(tile): update tile button padding

packages/apps/workshop/stories/design-system/components/skeleton/skeleton-webcomponent.stories.js, packages/apps/workshop/stories/design-system/components/skeleton/skeleton.story.mdx
No specs for now. So I'm just moving the category component.
=> docs(skeleton): update documentation stories
